
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - /config
  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.1.0.0/16
    - 10.100.0.0/16
    - 10.200.0.0/16
    
recorder:
  purge_keep_days: 7
  
input_boolean: !include input_boolean.yaml

input_datetime: !include input_datetime.yaml

# sensor: !include sensor.yaml

binary_sensor: !include binary_sensor.yaml

panel_custom: !include panel_custom.yaml

# climate: !include climate.yaml

# switch: !include switch.yaml

mqtt: !include mqtt.yaml
